services:
  alatrafclinic-api:
    container_name: alatrafclinic-api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "2003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Aden
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=alatrafclinicDb;User=sa;Password=YourStrong@Password1;TrustServerCertificate=True;MultipleActiveResultSets=True
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      - sqlserver
      - seq
    networks:
      - alatrafclinic-net
    restart: on-failure

  sqlserver:
    container_name: alatrafclinic-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password1
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - alatrafclinic-net
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
      - ./containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    networks:
      - alatrafclinic-net
    ports:
      - "15341:5341"
      - "18081:80"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./containers/prometheus:/etc/prometheus:ro
    ports:
      - "9090:9090"
    networks:
      - alatrafclinic-net
    depends_on:
      - alatrafclinic-api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=YourStrongPwd
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - alatrafclinic-net
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  sqlserver-data: {}
  grafana-data: {}

networks:
  alatrafclinic-net:
    driver: bridge
